// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vpn.proto

package v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Country entity
type Country struct {
	// unique
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// code
	Code                 string   `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Country) Reset()         { *m = Country{} }
func (m *Country) String() string { return proto.CompactTextString(m) }
func (*Country) ProtoMessage()    {}
func (*Country) Descriptor() ([]byte, []int) {
	return fileDescriptor_vpn_afadb66609a0a799, []int{0}
}
func (m *Country) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Country.Unmarshal(m, b)
}
func (m *Country) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Country.Marshal(b, m, deterministic)
}
func (dst *Country) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Country.Merge(dst, src)
}
func (m *Country) XXX_Size() int {
	return xxx_messageInfo_Country.Size(m)
}
func (m *Country) XXX_DiscardUnknown() {
	xxx_messageInfo_Country.DiscardUnknown(m)
}

var xxx_messageInfo_Country proto.InternalMessageInfo

func (m *Country) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Country) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Country) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

// VPNServer entity
type VPNServer struct {
	// unique id
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// hostname
	HostName string `protobuf:"bytes,2,opt,name=hostName,proto3" json:"hostName,omitempty"`
	// IP address
	Ip string `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	// score
	Score int32 `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`
	// ping
	Ping int32 `protobuf:"varint,5,opt,name=ping,proto3" json:"ping,omitempty"`
	// speed
	Speed int64 `protobuf:"varint,6,opt,name=speed,proto3" json:"speed,omitempty"`
	// country
	Country *Country `protobuf:"bytes,7,opt,name=country,proto3" json:"country,omitempty"`
	// number of VPN sessions
	NumVPNSessions int32 `protobuf:"varint,8,opt,name=numVPNSessions,proto3" json:"numVPNSessions,omitempty"`
	// uptime
	Uptime int64 `protobuf:"varint,9,opt,name=uptime,proto3" json:"uptime,omitempty"`
	// total of users
	TotalUsers int32 `protobuf:"varint,10,opt,name=totalUsers,proto3" json:"totalUsers,omitempty"`
	// total traffics
	TotalTraffic int64 `protobuf:"varint,11,opt,name=totalTraffic,proto3" json:"totalTraffic,omitempty"`
	// log type
	LogType string `protobuf:"bytes,12,opt,name=logType,proto3" json:"logType,omitempty"`
	// operator
	Operator string `protobuf:"bytes,13,opt,name=operator,proto3" json:"operator,omitempty"`
	// message
	Message string `protobuf:"bytes,14,opt,name=message,proto3" json:"message,omitempty"`
	// OpenVPN config
	OpenVPNConfig string `protobuf:"bytes,15,opt,name=openVPNConfig,proto3" json:"openVPNConfig,omitempty"`
	// created time
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,16,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	// updated time
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,17,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *VPNServer) Reset()         { *m = VPNServer{} }
func (m *VPNServer) String() string { return proto.CompactTextString(m) }
func (*VPNServer) ProtoMessage()    {}
func (*VPNServer) Descriptor() ([]byte, []int) {
	return fileDescriptor_vpn_afadb66609a0a799, []int{1}
}
func (m *VPNServer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VPNServer.Unmarshal(m, b)
}
func (m *VPNServer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VPNServer.Marshal(b, m, deterministic)
}
func (dst *VPNServer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VPNServer.Merge(dst, src)
}
func (m *VPNServer) XXX_Size() int {
	return xxx_messageInfo_VPNServer.Size(m)
}
func (m *VPNServer) XXX_DiscardUnknown() {
	xxx_messageInfo_VPNServer.DiscardUnknown(m)
}

var xxx_messageInfo_VPNServer proto.InternalMessageInfo

func (m *VPNServer) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *VPNServer) GetHostName() string {
	if m != nil {
		return m.HostName
	}
	return ""
}

func (m *VPNServer) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *VPNServer) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *VPNServer) GetPing() int32 {
	if m != nil {
		return m.Ping
	}
	return 0
}

func (m *VPNServer) GetSpeed() int64 {
	if m != nil {
		return m.Speed
	}
	return 0
}

func (m *VPNServer) GetCountry() *Country {
	if m != nil {
		return m.Country
	}
	return nil
}

func (m *VPNServer) GetNumVPNSessions() int32 {
	if m != nil {
		return m.NumVPNSessions
	}
	return 0
}

func (m *VPNServer) GetUptime() int64 {
	if m != nil {
		return m.Uptime
	}
	return 0
}

func (m *VPNServer) GetTotalUsers() int32 {
	if m != nil {
		return m.TotalUsers
	}
	return 0
}

func (m *VPNServer) GetTotalTraffic() int64 {
	if m != nil {
		return m.TotalTraffic
	}
	return 0
}

func (m *VPNServer) GetLogType() string {
	if m != nil {
		return m.LogType
	}
	return ""
}

func (m *VPNServer) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *VPNServer) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *VPNServer) GetOpenVPNConfig() string {
	if m != nil {
		return m.OpenVPNConfig
	}
	return ""
}

func (m *VPNServer) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *VPNServer) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

// List country request
type ListCountriesRequest struct {
	// api version
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCountriesRequest) Reset()         { *m = ListCountriesRequest{} }
func (m *ListCountriesRequest) String() string { return proto.CompactTextString(m) }
func (*ListCountriesRequest) ProtoMessage()    {}
func (*ListCountriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_vpn_afadb66609a0a799, []int{2}
}
func (m *ListCountriesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCountriesRequest.Unmarshal(m, b)
}
func (m *ListCountriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCountriesRequest.Marshal(b, m, deterministic)
}
func (dst *ListCountriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCountriesRequest.Merge(dst, src)
}
func (m *ListCountriesRequest) XXX_Size() int {
	return xxx_messageInfo_ListCountriesRequest.Size(m)
}
func (m *ListCountriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCountriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCountriesRequest proto.InternalMessageInfo

func (m *ListCountriesRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

// List country response
type ListCountriesResponse struct {
	// api version
	Api string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	// list countries
	Data                 []*Country `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListCountriesResponse) Reset()         { *m = ListCountriesResponse{} }
func (m *ListCountriesResponse) String() string { return proto.CompactTextString(m) }
func (*ListCountriesResponse) ProtoMessage()    {}
func (*ListCountriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_vpn_afadb66609a0a799, []int{3}
}
func (m *ListCountriesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCountriesResponse.Unmarshal(m, b)
}
func (m *ListCountriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCountriesResponse.Marshal(b, m, deterministic)
}
func (dst *ListCountriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCountriesResponse.Merge(dst, src)
}
func (m *ListCountriesResponse) XXX_Size() int {
	return xxx_messageInfo_ListCountriesResponse.Size(m)
}
func (m *ListCountriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCountriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCountriesResponse proto.InternalMessageInfo

func (m *ListCountriesResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ListCountriesResponse) GetData() []*Country {
	if m != nil {
		return m.Data
	}
	return nil
}

// List VPN servers request
type ListVPNServerRequest struct {
	// api version
	Api string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	// country code
	CountryCode          string   `protobuf:"bytes,2,opt,name=countryCode,proto3" json:"countryCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListVPNServerRequest) Reset()         { *m = ListVPNServerRequest{} }
func (m *ListVPNServerRequest) String() string { return proto.CompactTextString(m) }
func (*ListVPNServerRequest) ProtoMessage()    {}
func (*ListVPNServerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_vpn_afadb66609a0a799, []int{4}
}
func (m *ListVPNServerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListVPNServerRequest.Unmarshal(m, b)
}
func (m *ListVPNServerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListVPNServerRequest.Marshal(b, m, deterministic)
}
func (dst *ListVPNServerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListVPNServerRequest.Merge(dst, src)
}
func (m *ListVPNServerRequest) XXX_Size() int {
	return xxx_messageInfo_ListVPNServerRequest.Size(m)
}
func (m *ListVPNServerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListVPNServerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListVPNServerRequest proto.InternalMessageInfo

func (m *ListVPNServerRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ListVPNServerRequest) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

// List VPN servers response {
type ListVPNServerResponse struct {
	// api version
	Api string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	// list VPN servers
	Data                 []*VPNServer `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ListVPNServerResponse) Reset()         { *m = ListVPNServerResponse{} }
func (m *ListVPNServerResponse) String() string { return proto.CompactTextString(m) }
func (*ListVPNServerResponse) ProtoMessage()    {}
func (*ListVPNServerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_vpn_afadb66609a0a799, []int{5}
}
func (m *ListVPNServerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListVPNServerResponse.Unmarshal(m, b)
}
func (m *ListVPNServerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListVPNServerResponse.Marshal(b, m, deterministic)
}
func (dst *ListVPNServerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListVPNServerResponse.Merge(dst, src)
}
func (m *ListVPNServerResponse) XXX_Size() int {
	return xxx_messageInfo_ListVPNServerResponse.Size(m)
}
func (m *ListVPNServerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListVPNServerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListVPNServerResponse proto.InternalMessageInfo

func (m *ListVPNServerResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ListVPNServerResponse) GetData() []*VPNServer {
	if m != nil {
		return m.Data
	}
	return nil
}

// VPNGateCrawler request
type VPNGateCrawlerRequest struct {
	// api version
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VPNGateCrawlerRequest) Reset()         { *m = VPNGateCrawlerRequest{} }
func (m *VPNGateCrawlerRequest) String() string { return proto.CompactTextString(m) }
func (*VPNGateCrawlerRequest) ProtoMessage()    {}
func (*VPNGateCrawlerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_vpn_afadb66609a0a799, []int{6}
}
func (m *VPNGateCrawlerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VPNGateCrawlerRequest.Unmarshal(m, b)
}
func (m *VPNGateCrawlerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VPNGateCrawlerRequest.Marshal(b, m, deterministic)
}
func (dst *VPNGateCrawlerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VPNGateCrawlerRequest.Merge(dst, src)
}
func (m *VPNGateCrawlerRequest) XXX_Size() int {
	return xxx_messageInfo_VPNGateCrawlerRequest.Size(m)
}
func (m *VPNGateCrawlerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VPNGateCrawlerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VPNGateCrawlerRequest proto.InternalMessageInfo

func (m *VPNGateCrawlerRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

// VPNGateCrawler response
type VPNGateCrawlerResponse struct {
	// api version
	Api string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	// list vpn servers
	Data                 []*VPNServer `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *VPNGateCrawlerResponse) Reset()         { *m = VPNGateCrawlerResponse{} }
func (m *VPNGateCrawlerResponse) String() string { return proto.CompactTextString(m) }
func (*VPNGateCrawlerResponse) ProtoMessage()    {}
func (*VPNGateCrawlerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_vpn_afadb66609a0a799, []int{7}
}
func (m *VPNGateCrawlerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VPNGateCrawlerResponse.Unmarshal(m, b)
}
func (m *VPNGateCrawlerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VPNGateCrawlerResponse.Marshal(b, m, deterministic)
}
func (dst *VPNGateCrawlerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VPNGateCrawlerResponse.Merge(dst, src)
}
func (m *VPNGateCrawlerResponse) XXX_Size() int {
	return xxx_messageInfo_VPNGateCrawlerResponse.Size(m)
}
func (m *VPNGateCrawlerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VPNGateCrawlerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VPNGateCrawlerResponse proto.InternalMessageInfo

func (m *VPNGateCrawlerResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *VPNGateCrawlerResponse) GetData() []*VPNServer {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Country)(nil), "v1.Country")
	proto.RegisterType((*VPNServer)(nil), "v1.VPNServer")
	proto.RegisterType((*ListCountriesRequest)(nil), "v1.ListCountriesRequest")
	proto.RegisterType((*ListCountriesResponse)(nil), "v1.ListCountriesResponse")
	proto.RegisterType((*ListVPNServerRequest)(nil), "v1.ListVPNServerRequest")
	proto.RegisterType((*ListVPNServerResponse)(nil), "v1.ListVPNServerResponse")
	proto.RegisterType((*VPNGateCrawlerRequest)(nil), "v1.VPNGateCrawlerRequest")
	proto.RegisterType((*VPNGateCrawlerResponse)(nil), "v1.VPNGateCrawlerResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceClient interface {
	// crawl all vpn server
	VPNGateCrawler(ctx context.Context, in *VPNGateCrawlerRequest, opts ...grpc.CallOption) (*VPNGateCrawlerResponse, error)
	// List all country that have available VPN servers
	ListCountries(ctx context.Context, in *ListCountriesRequest, opts ...grpc.CallOption) (*ListCountriesResponse, error)
	// List all VPN servers
	ListVPNServers(ctx context.Context, in *ListVPNServerRequest, opts ...grpc.CallOption) (*ListVPNServerResponse, error)
}

type serviceClient struct {
	cc *grpc.ClientConn
}

func NewServiceClient(cc *grpc.ClientConn) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) VPNGateCrawler(ctx context.Context, in *VPNGateCrawlerRequest, opts ...grpc.CallOption) (*VPNGateCrawlerResponse, error) {
	out := new(VPNGateCrawlerResponse)
	err := c.cc.Invoke(ctx, "/v1.Service/VPNGateCrawler", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) ListCountries(ctx context.Context, in *ListCountriesRequest, opts ...grpc.CallOption) (*ListCountriesResponse, error) {
	out := new(ListCountriesResponse)
	err := c.cc.Invoke(ctx, "/v1.Service/ListCountries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) ListVPNServers(ctx context.Context, in *ListVPNServerRequest, opts ...grpc.CallOption) (*ListVPNServerResponse, error) {
	out := new(ListVPNServerResponse)
	err := c.cc.Invoke(ctx, "/v1.Service/ListVPNServers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
type ServiceServer interface {
	// crawl all vpn server
	VPNGateCrawler(context.Context, *VPNGateCrawlerRequest) (*VPNGateCrawlerResponse, error)
	// List all country that have available VPN servers
	ListCountries(context.Context, *ListCountriesRequest) (*ListCountriesResponse, error)
	// List all VPN servers
	ListVPNServers(context.Context, *ListVPNServerRequest) (*ListVPNServerResponse, error)
}

func RegisterServiceServer(s *grpc.Server, srv ServiceServer) {
	s.RegisterService(&_Service_serviceDesc, srv)
}

func _Service_VPNGateCrawler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VPNGateCrawlerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).VPNGateCrawler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Service/VPNGateCrawler",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).VPNGateCrawler(ctx, req.(*VPNGateCrawlerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_ListCountries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCountriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).ListCountries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Service/ListCountries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).ListCountries(ctx, req.(*ListCountriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_ListVPNServers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVPNServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).ListVPNServers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Service/ListVPNServers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).ListVPNServers(ctx, req.(*ListVPNServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Service_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VPNGateCrawler",
			Handler:    _Service_VPNGateCrawler_Handler,
		},
		{
			MethodName: "ListCountries",
			Handler:    _Service_ListCountries_Handler,
		},
		{
			MethodName: "ListVPNServers",
			Handler:    _Service_ListVPNServers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vpn.proto",
}

func init() { proto.RegisterFile("vpn.proto", fileDescriptor_vpn_afadb66609a0a799) }

var fileDescriptor_vpn_afadb66609a0a799 = []byte{
	// 622 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x52, 0x4f, 0x6f, 0x13, 0x3f,
	0x10, 0x55, 0x36, 0x69, 0xd3, 0x4c, 0x9a, 0xb4, 0x3f, 0xff, 0xda, 0xca, 0x5d, 0x21, 0x1a, 0x56,
	0x80, 0x82, 0x44, 0x13, 0xb5, 0x5c, 0xb8, 0x56, 0x39, 0x54, 0xaa, 0x4a, 0x54, 0x2d, 0xa5, 0x07,
	0x38, 0xb9, 0xbb, 0x93, 0xc5, 0x52, 0xb2, 0x36, 0xb6, 0x93, 0xaa, 0x57, 0xae, 0x1c, 0xb9, 0xf2,
	0xad, 0xf8, 0x0a, 0x7c, 0x10, 0x64, 0x7b, 0xf3, 0xbf, 0x85, 0x03, 0xa7, 0xf5, 0xbc, 0x79, 0xef,
	0xcd, 0xec, 0xcc, 0x40, 0x6d, 0x22, 0xf3, 0x8e, 0x54, 0xc2, 0x08, 0x12, 0x4c, 0x4e, 0xc2, 0xa3,
	0x4c, 0x88, 0x6c, 0x88, 0x5d, 0x87, 0xdc, 0x8e, 0x07, 0x5d, 0xc3, 0x47, 0xa8, 0x0d, 0x1b, 0x49,
	0x4f, 0x0a, 0x9f, 0x14, 0x04, 0x26, 0x79, 0x97, 0xe5, 0xb9, 0x30, 0xcc, 0x70, 0x91, 0xeb, 0x22,
	0xfb, 0xda, 0x7d, 0x92, 0xe3, 0x0c, 0xf3, 0x63, 0x7d, 0xc7, 0xb2, 0x0c, 0x55, 0x57, 0x48, 0xc7,
	0x58, 0x67, 0x47, 0x67, 0x50, 0xed, 0x89, 0x71, 0x6e, 0xd4, 0x3d, 0x69, 0x42, 0xc0, 0x53, 0x5a,
	0x6a, 0x95, 0xda, 0x1b, 0x71, 0xc0, 0x53, 0x42, 0xa0, 0x92, 0xb3, 0x11, 0xd2, 0xa0, 0x55, 0x6a,
	0xd7, 0x62, 0xf7, 0xb6, 0x58, 0x22, 0x52, 0xa4, 0x65, 0x8f, 0xd9, 0x77, 0xf4, 0xa3, 0x02, 0xb5,
	0x9b, 0xab, 0xfe, 0x7b, 0x54, 0x13, 0x54, 0x6b, 0x2e, 0x21, 0x6c, 0x7d, 0x16, 0xda, 0xf4, 0xe7,
	0x4e, 0xb3, 0xd8, 0x71, 0x65, 0xe1, 0x15, 0x70, 0x49, 0xf6, 0x60, 0x43, 0x27, 0x42, 0x21, 0xad,
	0x38, 0xb9, 0x0f, 0x6c, 0x4d, 0xc9, 0xf3, 0x8c, 0x6e, 0x38, 0xd0, 0xbd, 0x1d, 0x53, 0x22, 0xa6,
	0x74, 0xb3, 0x55, 0x6a, 0x97, 0x63, 0x1f, 0x90, 0x17, 0x50, 0x4d, 0xfc, 0xcf, 0xd0, 0x6a, 0xab,
	0xd4, 0xae, 0x9f, 0xd6, 0x3b, 0x93, 0x93, 0x4e, 0xf1, 0x7f, 0xf1, 0x34, 0x47, 0x5e, 0x42, 0x33,
	0x1f, 0x8f, 0x5c, 0xcb, 0x5a, 0xdb, 0x59, 0xd0, 0x2d, 0x67, 0xbd, 0x82, 0x92, 0x03, 0xd8, 0x1c,
	0x4b, 0x3b, 0x7c, 0x5a, 0x73, 0x55, 0x8a, 0x88, 0x3c, 0x05, 0x30, 0xc2, 0xb0, 0xe1, 0x07, 0x8d,
	0x4a, 0x53, 0x70, 0xda, 0x05, 0x84, 0x44, 0xb0, 0xed, 0xa2, 0x6b, 0xc5, 0x06, 0x03, 0x9e, 0xd0,
	0xba, 0x53, 0x2f, 0x61, 0x84, 0x42, 0x75, 0x28, 0xb2, 0xeb, 0x7b, 0x89, 0x74, 0xdb, 0xfd, 0xff,
	0x34, 0xb4, 0x03, 0x13, 0x12, 0x15, 0x33, 0x42, 0xd1, 0x86, 0x1f, 0xd8, 0x34, 0xb6, 0xaa, 0x11,
	0x6a, 0xcd, 0x32, 0xa4, 0x4d, 0xaf, 0x2a, 0x42, 0xf2, 0x1c, 0x1a, 0x42, 0x62, 0x7e, 0x73, 0xd5,
	0xef, 0x89, 0x7c, 0xc0, 0x33, 0xba, 0xe3, 0xf2, 0xcb, 0x20, 0x79, 0x0b, 0xb5, 0x44, 0x21, 0x33,
	0x98, 0x9e, 0x19, 0xba, 0xeb, 0x46, 0x14, 0x76, 0xfc, 0x35, 0x75, 0xa6, 0xe7, 0xd6, 0xb9, 0x9e,
	0x9e, 0x5b, 0x3c, 0x27, 0x5b, 0xe5, 0x58, 0xa6, 0x85, 0xf2, 0xbf, 0xbf, 0x2b, 0x67, 0xe4, 0xa8,
	0x0d, 0x7b, 0x97, 0x5c, 0x1b, 0xbf, 0x05, 0x8e, 0x3a, 0xc6, 0x2f, 0x63, 0xd4, 0x86, 0xec, 0x42,
	0x99, 0x49, 0xee, 0x2e, 0xa5, 0x16, 0xdb, 0x67, 0x74, 0x01, 0xfb, 0x2b, 0x4c, 0x2d, 0x45, 0xae,
	0x71, 0x9d, 0x4a, 0x8e, 0xa0, 0x92, 0x32, 0xc3, 0x68, 0xd0, 0x2a, 0xaf, 0xae, 0xd9, 0x25, 0xa2,
	0x0b, 0x5f, 0x75, 0x76, 0x97, 0x8f, 0x56, 0x25, 0x2d, 0xa8, 0x17, 0x87, 0xd1, 0xb3, 0x97, 0xed,
	0x6f, 0x74, 0x11, 0x8a, 0x2e, 0x7d, 0x5f, 0x0b, 0x5e, 0x8f, 0xf6, 0xf5, 0x6c, 0xa9, 0xaf, 0x86,
	0xed, 0x6b, 0x2e, 0xf3, 0x9d, 0xbd, 0x82, 0xfd, 0x9b, 0xab, 0xfe, 0x39, 0x33, 0xd8, 0x53, 0xec,
	0x6e, 0xf8, 0x87, 0xd6, 0xa2, 0x77, 0x70, 0xb0, 0x4a, 0xfd, 0x87, 0xca, 0xa7, 0xdf, 0x02, 0xa8,
	0x5a, 0x80, 0x27, 0x48, 0xce, 0xa1, 0xb9, 0x6c, 0x4d, 0x0e, 0x0b, 0xc9, 0x7a, 0x67, 0x61, 0xf8,
	0x50, 0xaa, 0xe8, 0xe4, 0x13, 0x34, 0x96, 0x96, 0x46, 0xa8, 0x25, 0x3f, 0xb4, 0xf1, 0xf0, 0xf0,
	0x81, 0x8c, 0x77, 0x89, 0xf6, 0xbf, 0xfe, 0xfc, 0xf5, 0x3d, 0xd8, 0x21, 0x8d, 0xee, 0xe4, 0xa4,
	0x9b, 0xcc, 0xbc, 0x3e, 0x42, 0x73, 0x69, 0xf2, 0x0b, 0xee, 0xab, 0x9b, 0x9d, 0xbb, 0xaf, 0xed,
	0x29, 0xfa, 0xdf, 0xb9, 0x37, 0x48, 0xdd, 0xba, 0x6b, 0xef, 0x74, 0xbb, 0xe9, 0xce, 0xf6, 0xcd,
	0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9f, 0xda, 0x5a, 0x93, 0x7e, 0x05, 0x00, 0x00,
}
