apiVersion: v1
kind: Secret
metadata:
  name: ${SERVICE_NAME}
type: Opaque
data:
  DB_HOST: ${DB_HOST}
  DB_USER: ${DB_USER}
  DB_PASSWORD: ${DB_PASSWORD}
  DB_SCHEMA: ${DB_SCHEMA}
  DB_PORT: ${DB_PORT}
  API_KEY: ${API_KEY}
  APPLE_SHARED_SECRET_KEY: ${APPLE_SHARED_SECRET_KEY}


