apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .ServiceName }}
  labels:
    app: {{ .ServiceName }}
spec:
  replicas: 1
#  strategy:
#    type: RollingUpdate
#    rollingUpdate:
#      maxUnavailable: 50%
#      maxSurge: 1
  template:
    metadata:
      labels:
        app: {{ .ServiceName }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - totalcoinwallet.com
      containers:
      - name: {{ .ServiceName }}
        image: reg.ahiho.com/ahiho/{{ .ServiceName }}:{{ .Release }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: {{ .ServiceName }}-cm
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 25
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 25
          periodSeconds: 30
#        resources:
#          limits:
#            cpu: 500m
#            memory: 256Mi
#          requests:
#            cpu: 500m
#            memory: 256Mi
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
      - name: regcred

